# Generated by Django 6.1 on 2026-08-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='quantidade_total',
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
