# Generated by Django 5.2.12 on 2026-08-23 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_alter_autor_id_alter_categoria_id_alter_livro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livro.editora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(related_name='livros', to='livro.categoria'),
        ),
    ]
