# Generated by Django 5.2.12 on 2026-08-25 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editora', '0001_initial'),
        ('livro', '0004_editora_remove_livro_isbn_remove_livro_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='editora.editora'),
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
    ]
