# Generated by Django 6.1 on 2026-08-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_autor_id_alter_categoria_id_alter_editora_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
