# Generated by Django 5.2.12 on 2026-09-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_id'),
        ('categoria', '0002_alter_categoria_id'),
        ('livro', '0007_alter_autor_id_alter_categoria_id_alter_livro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='autor.autor'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(related_name='livros', to='categoria.categoria'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
