# Generated by Django 5.2.12 on 2026-08-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=None, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
