# Generated by Django 5.2.12 on 2026-08-23 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livro', '0004_editora_remove_livro_isbn_remove_livro_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_prevista_devolucao', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('renovado', models.BooleanField(default=False)),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_como_bibliotecario', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livro')),
            ],
        ),
    ]
