# Generated by Django 5.2.12 on 2026-08-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
        ('livro', '0004_editora_remove_livro_isbn_remove_livro_categoria_and_more'),
        ('usuario', '0002_remove_usuario_telefone_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='bibliotecario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_como_bibliotecario', to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_como_cliente', to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livro.livro'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
    ]
