# Generated by Django 6.1 on 2026-08-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_alter_emprestimo_bibliotecario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
